protected/controllers/NewsController.php
<?php

class NewsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow all users to perform 'index' and 'view' actions
				'actions' => array('index', 'view', 'alumnus'),
				'users'   => array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions' => array('create', 'update'),
				'users'   => array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions' => array('admin', 'delete'),
				'users'   => array('admin'),
			),
			array('deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view', array(
			'model' => $this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new News;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['News'])) {
			$model->attributes = $_POST['News'];
			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array(
			'model' => $model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$this->setPageTitle("Редагування новин");
		$model = $this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['News'])) {
			$model->attributes = $_POST['News'];
			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
			'model' => $model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if (!isset($_GET['ajax'])) {
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex($user_id = null)
	{
		$this->setPageTitle("Останні новини");
		$dataProvider = new CActiveDataProvider('News', array(
			'criteria'   => array(
				'condition' => "`status`='" . News::STATUS_PUBLISHED . "'",
				'with'      => array('author_created', 'category'),
				'order'     => 'created DESC',
			),
			'pagination' => array(
				'pageSize' => 5
			)
		));
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAlumnus()
	{
		$this->setPageTitle("Новини від випускників");
		$user_news = new CActiveDataProvider('News', array(
			'criteria'   => array(
				'limit'     => 10,
				'order'     => 'created DESC',
				'condition' => "`author`!=0 and `status`='" . News::STATUS_PUBLISHED . "'",
				'with'      => 'author_created'
			),
			'pagination' => array(
				'pageSize' => 10,
			)
		));
		$this->render('alumnus', array(
			'dataProvider' => $user_news
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model = new News('search');
		$model->unsetAttributes(); // clear any default values
		if (isset($_GET['News'])) {
			$model->attributes = $_GET['News'];
		}

		$this->render('admin', array(
			'model' => $model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model = News::model()->findByPk($id);
		if ($model === null) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'news-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/PagesController.php
<?php

class PagesController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('view'),
				'users'=>array('*'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','create','update'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($slug)
	{
        $model = Pages::model()->findByAttributes(array('slug'=>$slug));
        if(is_null($model) || $model->visible == Pages::STATUS_HIDE)
            throw new CHttpException(404,'The requested page does not exist.');
        $this->setPageTitle($model->title);
		$this->render('view',array(
			'model'=>$model,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Pages;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Pages']))
		{
			$model->attributes=$_POST['Pages'];
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Pages']))
		{
			$model->attributes=$_POST['Pages'];
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Pages');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Pages('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Pages']))
			$model->attributes=$_GET['Pages'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Pages the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Pages::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Pages $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='pages-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete, photodel', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow all users to perform 'index' and 'view' actions
				'actions' => array('create', 'index', 'view'),
				'users'   => array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions' => array('update', 'photo', 'photodel'),
				'users'   => array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions' => array('admin', 'delete', 'mail'),
				'users'   => array('admin'),
			),
			array('deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->setPageTitle('Профіль користувача');
		$this->render('view', array(
			'model' => $this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate($key)
	{
		$this->setPageTitle('Реєстрація користувача');
		if (!Yii::app()->user->isGuest) {
			Yii::app()->user->logout(); // logout user to be registreted
			$this->refresh();
		}
		if (strlen($key) != 32) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		$invite = Invite::model()->find('`key`=:key', array(':key' => $key));
		if ($invite === null || $invite->key !== $key) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		if ($invite->used == 1) {
			throw new CHttpException(404, "Вибачте, але це запрошення вже було використано.");
		}

		$model = new User;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);
		if (isset($_POST['User'])) {
			$model->attributes = $_POST['User'];
			if ($model->validate()) {
				$model->password = hash('sha512', $model->password);
				$model->save(false);
				$invite->used = 1;
				$invite->save();
				Yii::app()->user->setFlash('info', 'Щиро дякуємо за реєстрацію. Як тільки сайт запрацює на повну потужність, ми Вас обов’язково повідомимо листом.');
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$model->email = $invite->email;
		for ($i = 1992; $i < date('Y'); $i++) {
			$years[$i] = $i;
		}
		$this->render('create', array(
			'model' => $model,
			'years' => $years
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$this->setPageTitle('Редагування профілю');
		$model = $this->loadModel($id);
		if (Yii::app()->user->getState('email') !== $model->email && Yii::app()->user->name !== 'admin') {
			throw new CHttpException(404, 'The requested page does not exist.');
		}

		$this->performAjaxValidation($model);
		if (isset($_POST['User'])) {
			$pass = $_POST['User']['password'];
			$old_pass = $model->password;

			$model->attributes = $_POST['User'];
			$model->password = $old_pass;
			if (strlen($pass) >= 8 && $old_pass !== hash('sha512', $pass)) {
				$model->password = hash('sha512', $pass);
			}
			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		for ($i = 1992; $i < date('Y'); $i++) {
			$years[$i] = $i;
		}
		$model->password = '';
		$this->render('update', array(
			'model' => $model,
			'years' => $years
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if (!isset($_GET['ajax'])) {
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->setPageTitle('Випускники');
		$c = Yii::app()->db->createCommand();
		$users = $c->select()->from('users')->order('enter ASC,surname')->queryAll();
		foreach ($users as $u) {
			$users[$u['year']][] = $u;
		}
		$c->reset();
		$years = $c->select('year as year')->from('users')->group('year')->order('year DESC')->queryAll();
		$this->render('index', array(
			'users' => $users,
			'years' => $years
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model = new User('search');
		$model->unsetAttributes(); // clear any default values
		if (isset($_GET['User'])) {
			$model->attributes = $_GET['User'];
		}

		$this->render('admin', array(
			'model' => $model,
		));
	}

	public function actionPhoto()
	{
		$this->setPageTitle('Редагування фото');
		$model = new PhotoForm;
		if (isset($_POST['PhotoForm'])) {
			$model->attributes = $_POST['PhotoForm'];
			if ($model->validate()) {
				$model->image = EUploadedImage::getInstance($model, 'photo');
				$model->image->maxWidth = 240;
				$model->image->maxHeight = 320;
				$model->image->thumb = array(
					'maxWidth'  => 64,
					'maxHeight' => 64,
					'dir'       => 't',
					'prefix'    => 't',
				);
				$name = substr(md5(time() . Yii::app()->user->name), 0, Yii::app()->params['photoLength']).'.jpg'; // name of file
				if ($model->image->saveAs(Yii::getPathOfAlias('webroot') . Yii::app()->params['uploadFolder'] . $name)) {
					$this->setPhoto($name);
					Yii::app()->user->setFlash('img_good', 'Зображення було успішно змінено.');
				} else {
					Yii::app()->user->setFlash('img_bad', 'Вибачте, але сталася помилка. Спробуйте пізніше.');
				}
			}
		}
		$this->render('_photo', array(
			'photo' => $model,
			'model' => $this->loadModel(Yii::app()->user->id)
		));
	}

	public function actionPhotoDel()
	{
		$user = User::model()->findByPk(Yii::app()->user->id);
		if (!is_null($user) && $user !== false && strlen($user->photo) == Yii::app()->params['photoLength']) { // sorry for dogs
			@unlink(Yii::getpathOfAlias('webroot') . Yii::app()->params['uploadFolder'] . $user->photo . '.jpg');
			@unlink(Yii::getpathOfAlias('webroot') . Yii::app()->params['uploadFolderTh'] . 't' . $user->photo . '.jpg');
			$this->setPhoto('');
		}
		$this->redirect(array('update', 'id' => Yii::app()->user->id));
	}

	public function setPhoto($name)
	{
		$command = Yii::app()->db->createCommand();
		if ($command->update('users', array(
				'photo' => $name,
			),
			'id=:id', array(':id' => Yii::app()->user->id))
		) {
			return true;
		}
		return false;
	}

	public function actionMail()
	{
		$this->setPageTitle('Розсилка');
		$form = new MailForm;
		if (isset($_POST['MailForm'])) {
			$form->attributes = $_POST['MailForm'];
			$u = User::model()->findAll();
			$mailer = Yii::app()->mail;
			foreach ($u as $a) {
				//send mail for everyone
				$mail = $mailer->newMessage(array(
					'subject' => $form->subject,
					'from'    => Yii::app()->params['mail'],
					'to'      => $a->email,
				));
				$mail->view = array('subscription', 'message' => $form->body);
				if (!$mailer->send($mail)) {
					Yii::app()->user->setFlash('fail', 'Помилка розсилки. Спробуйте пізніше.');
				}
			}
			if (!Yii::app()->user->getFlash('fail')) {
				Yii::app()->user->setFlash('success', 'Розсилка успішно відправлена.');
			}
			$this->refresh();
		}
		$this->render('mail', array(
			'model' => $form
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model = User::model()->findByPk($id);
		if ($model === null) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'user-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta charset="utf-8">
	<link rel="stylesheet/less" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/styles.less">
	<script src="//cdnjs.cloudflare.com/ajax/libs/less.js/1.6.2/less.min.js" type="text/javascript"></script>
	<link
		href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAFo9M/3AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAhhJREFUeNpiLDrgwgACTAwQ8B8ggBiBIlOBDBEWIJENEgIIIJDIaiC9C4hnw9TyQjlsIAGAAAKpaALSdUAcClLJBOVoAfEsIHYHGfYfakUFECuBVDAC8Rsg1gDi0wABBDJjIpCRD1UVA8SLoYpAYCNIRykQBwOxKhAHMCDAFyAWBtnhD8Qgt74AYgkgToAqWAvEQiAT9gLxFiCuBeJ1QCwJxGuAeCsQ+wAEECM0NJYC8R4gng/VPRmImYE4C2TFEyCWgYUWELcDcS6UvwNkxUIo5xfU9c1A3AYV+w4ywQ2I46BhBzLhMhDbAnEEyF0s0DC4BsQmUF26QPwRiJeDTARZMQOIk4D4DDQ8QNacgtIdTNCQ6wPiGqii60BsBjVNnwXqoOdArAnEyVA3pIMkgbgBIMBA4cAKZNwE4h9AvAka4epQE/qB+CvU26JAfAuIH0I9Zg3EKiAbDkCdMAUpnlyBeCrUnV+g6WMSEE+HyoOCygGI5zBB4ywKKgGKln9Qm9SA+BMQi0GdD9L8GinlgALmAQvU9sfQMLaCplsDkCQDKiiCekMaKUarmJBMA/l3ARCDDL0AimYkzXeh6QMEdkLVmoJSGwtU0yOoDUVQvwYBsQIQ/0Ey5AzUVTpQfhoo3zBBFVkiKcyDJr5oqFNBuAuaUkKQ1JnAMkQKiAHEi4CYB5QAgfgpNFfCshbI7y1ALAdVAwKNQHwRANzVcuxoxnr4AAAAAElFTkSuQmCC"
		rel="icon" type="image/x-icon"/>
	<title><?php echo CHtml::encode($this->pageTitle) . " | " . Yii::app()->name; ?></title>

</head>

<body>

<div class="container" id="page">

	<div class="header">
		<a href="/">
			<div class="logo"></div>
		</a>

		<div class="title"><!-- <?php echo CHtml::encode(Yii::app()->name); ?>-->
			<h3>Національний університет «<a href="http://ukma.edu.ua/" title="Сайт університету">Києво-Могилянська
					Академія</a>»</h3>

			<h2>Випускники кафедри фізико-математичних наук</h2>
		</div>
		<div class="social">
			<div class="linkedin">
				<script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
				<script type="IN/Share" data-counter="right"></script>
			</div>
			<div class="twitter">
				<a href="https://twitter.com/share" class="twitter-share-button" data-lang="uk">Твіт</a>
				<script>!function (d, s, id) {
						var js, fjs = d.getElementsByTagName(s)[0];
						if (!d.getElementById(id)) {
							js = d.createElement(s);
							js.id = id;
							js.src = "//platform.twitter.com/widgets.js";
							fjs.parentNode.insertBefore(js, fjs);
						}
					}(document, "script", "twitter-wjs");</script>
			</div>

		</div>
	</div>
	<!-- header -->

	<div class="mainmenu">
		<?php
        $this->widget('zii.widgets.CMenu', array(
            'items' => CMap::mergeArray(
                    Pages::getMenu(),
                    array(
                        array('label' => 'Випускники', 'url' => array('/user/index')),
                        array('label' => 'Новини', 'url' => array('/news/index')),
                        array('label' => 'Профіль', 'url' => array('/user/view', 'id' => Yii::app()->user->id), 'visible' => !Yii::app()->user->isGuest && Yii::app()->user->name !== 'admin'
                        ),
                        array('label' => 'Вхід', 'url' => array('/site/login'), 'visible' => Yii::app()->user->isGuest),
                        array('label' => 'Вихід', 'url' => array('/site/logout'), 'visible' => !Yii::app()->user->isGuest),
                    ),
                    Pages::getMenu(Pages::MENU_END)
                )
        )); ?>
	</div>
	<!-- mainmenu -->

	<div class="navigation">
		<?php if (isset($this->breadcrumbs)): ?>
			<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
		<?php endif ?>



	</div>
    <?php if (!Yii::app()->user->isGuest && Yii::app()->user->name == 'admin'): ?>
        <!--begin block for admin -->
        <div class="administration">
            <div class="form_button"><?php echo CHtml::link('Додати новину', array('/news/create')); ?></div>
            <div class="form_button"><?php echo CHtml::link('Керування новинами', array('/news/admin')); ?></div>
            <div class="form_button"><?php echo CHtml::link('Надіслати запрошення', array('/invite/create')); ?></div>
            <div class="form_button"><?php echo CHtml::link('Розсилка', array('/user/mail')); ?></div>
            <div class="form_button"><?php echo CHtml::link('Додати сторінку', array('/pages/create')); ?></div>
            <div class="form_button"><?php echo CHtml::link('Керування сторінками', array('/pages/admin')); ?></div>
        </div>
        <br><br>
        <!--end block for admin-->
    <?php endif; ?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div class="footer">

		<a href="http://usic.at" title="Розробники сайту — команда Студентського Інтернет центру НаУМКА">
			<div class="usic_logo"></div>
		</a>

	</div>
	<!-- footer -->

</div>
<!-- page -->
<a href="#" class="scrollup" title="Вгору" style="display: inline;">
	<div class="scroll_img">&#x21e7;</div>
</a>
<!-- Yandex.Metrika counter --><script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter20076403 = new Ya.Metrika({id:20076403, webvisor:true, clickmap:true, trackLinks:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/20076403" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
</body>
</html>