protected/models/News.php
<?php

/**
 * This is the model class for table "{{news}}".
 *
 * The followings are the available columns in table '{{news}}':
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property string $deadline
 * @property integer $author
 * @property integer $created
 * @property integer $status
 * @property integer $type
 */
class News extends CActiveRecord
{
   
    const STATUS_PUBLISHED = 1;
    const STATUS_DRAFT     = 0; 
    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return News the static model class
     */
    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'news';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        return array(
            array('title, content, author, created, status', 'required','message'=>'{attribute} не має бути порожнім'),
            array('author, created, status', 'numerical', 'integerOnly'=>true),
            array('title', 'length', 'max'=>255),
            array('type','numerical','allowEmpty'=>Yii::app()->user->name!=='admin'),
            array('deadline','date','format'=>'dd-mm-yyyy','allowEmpty'=>true),
            array('id, title, content, author, created, status', 'safe', 'on'=>'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        return array(
           'author_created'=>array(self::BELONGS_TO,'User','author'),
           'category'=>array(self::BELONGS_TO,'Lookup','type') 
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'title' => 'Заголовок',
            'content' => 'Основний текст',
            'author' => 'Автор',
            'created' => 'Created',
            'status' => 'Статус',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria=new CDbCriteria;

        $criteria->compare('id',$this->id);
        $criteria->compare('title',$this->title,true);
        $criteria->compare('content',$this->content,true);
        $criteria->compare('author',$this->author);
        $criteria->compare('created',$this->created);
        $criteria->compare('status',$this->status);

        return new CActiveDataProvider($this, array(
            'criteria'=>$criteria,
        ));
    }

    public function beforeValidate() {
        if ($this->isNewRecord){
            $this->created = time();
            $this->author = Yii::app()->user->id;
        }
        return parent::beforeValidate();
    }
}

protected/controllers/NewsController.php
<?php

class NewsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow all users to perform 'index' and 'view' actions
				'actions' => array('index', 'view', 'alumnus'),
				'users'   => array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions' => array('create', 'update'),
				'users'   => array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions' => array('admin', 'delete'),
				'users'   => array('admin'),
			),
			array('deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view', array(
			'model' => $this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new News;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['News'])) {
			$model->attributes = $_POST['News'];
			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array(
			'model' => $model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$this->setPageTitle("Редагування новин");
		$model = $this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['News'])) {
			$model->attributes = $_POST['News'];
			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
			'model' => $model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if (!isset($_GET['ajax'])) {
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex($user_id = null)
	{
		$this->setPageTitle("Останні новини");
		$dataProvider = new CActiveDataProvider('News', array(
			'criteria'   => array(
				'condition' => "`status`='" . News::STATUS_PUBLISHED . "'",
				'with'      => array('author_created', 'category'),
				'order'     => 'created DESC',
			),
			'pagination' => array(
				'pageSize' => 5
			)
		));
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAlumnus()
	{
		$this->setPageTitle("Новини від випускників");
		$user_news = new CActiveDataProvider('News', array(
			'criteria'   => array(
				'limit'     => 10,
				'order'     => 'created DESC',
				'condition' => "`author`!=0 and `status`='" . News::STATUS_PUBLISHED . "'",
				'with'      => 'author_created'
			),
			'pagination' => array(
				'pageSize' => 10,
			)
		));
		$this->render('alumnus', array(
			'dataProvider' => $user_news
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model = new News('search');
		$model->unsetAttributes(); // clear any default values
		if (isset($_GET['News'])) {
			$model->attributes = $_GET['News'];
		}

		$this->render('admin', array(
			'model' => $model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model = News::model()->findByPk($id);
		if ($model === null) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'news-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete, photodel', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow all users to perform 'index' and 'view' actions
				'actions' => array('create', 'index', 'view'),
				'users'   => array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions' => array('update', 'photo', 'photodel'),
				'users'   => array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions' => array('admin', 'delete', 'mail'),
				'users'   => array('admin'),
			),
			array('deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->setPageTitle('Профіль користувача');
		$this->render('view', array(
			'model' => $this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate($key)
	{
		$this->setPageTitle('Реєстрація користувача');
		if (!Yii::app()->user->isGuest) {
			Yii::app()->user->logout(); // logout user to be registreted
			$this->refresh();
		}
		if (strlen($key) != 32) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		$invite = Invite::model()->find('`key`=:key', array(':key' => $key));
		if ($invite === null || $invite->key !== $key) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		if ($invite->used == 1) {
			throw new CHttpException(404, "Вибачте, але це запрошення вже було використано.");
		}

		$model = new User;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);
		if (isset($_POST['User'])) {
			$model->attributes = $_POST['User'];
			if ($model->validate()) {
				$model->password = hash('sha512', $model->password);
				$model->save(false);
				$invite->used = 1;
				$invite->save();
				Yii::app()->user->setFlash('info', 'Щиро дякуємо за реєстрацію. Як тільки сайт запрацює на повну потужність, ми Вас обов’язково повідомимо листом.');
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$model->email = $invite->email;
		for ($i = 1992; $i < date('Y'); $i++) {
			$years[$i] = $i;
		}
		$this->render('create', array(
			'model' => $model,
			'years' => $years
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$this->setPageTitle('Редагування профілю');
		$model = $this->loadModel($id);
		if (Yii::app()->user->getState('email') !== $model->email && Yii::app()->user->name !== 'admin') {
			throw new CHttpException(404, 'The requested page does not exist.');
		}

		$this->performAjaxValidation($model);
		if (isset($_POST['User'])) {
			$pass = $_POST['User']['password'];
			$old_pass = $model->password;

			$model->attributes = $_POST['User'];
			$model->password = $old_pass;
			if (strlen($pass) >= 8 && $old_pass !== hash('sha512', $pass)) {
				$model->password = hash('sha512', $pass);
			}
			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		for ($i = 1992; $i < date('Y'); $i++) {
			$years[$i] = $i;
		}
		$model->password = '';
		$this->render('update', array(
			'model' => $model,
			'years' => $years
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if (!isset($_GET['ajax'])) {
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->setPageTitle('Випускники');
		$c = Yii::app()->db->createCommand();
		$users = $c->select()->from('users')->order('enter ASC,surname')->queryAll();
		foreach ($users as $u) {
			$users[$u['year']][] = $u;
		}
		$c->reset();
		$years = $c->select('year as year')->from('users')->group('year')->order('year DESC')->queryAll();
		$this->render('index', array(
			'users' => $users,
			'years' => $years
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model = new User('search');
		$model->unsetAttributes(); // clear any default values
		if (isset($_GET['User'])) {
			$model->attributes = $_GET['User'];
		}

		$this->render('admin', array(
			'model' => $model,
		));
	}

	public function actionPhoto()
	{
		$this->setPageTitle('Редагування фото');
		$model = new PhotoForm;
		if (isset($_POST['PhotoForm'])) {
			$model->attributes = $_POST['PhotoForm'];
			if ($model->validate()) {
				$model->image = EUploadedImage::getInstance($model, 'photo');
				$model->image->maxWidth = 240;
				$model->image->maxHeight = 320;
				$model->image->thumb = array(
					'maxWidth'  => 64,
					'maxHeight' => 64,
					'dir'       => 't',
					'prefix'    => 't',
				);
				$name = substr(md5(time() . Yii::app()->user->name), 0, Yii::app()->params['photoLength']).'.jpg'; // name of file
				if ($model->image->saveAs(Yii::getPathOfAlias('webroot') . Yii::app()->params['uploadFolder'] . $name)) {
					$this->setPhoto($name);
					Yii::app()->user->setFlash('img_good', 'Зображення було успішно змінено.');
				} else {
					Yii::app()->user->setFlash('img_bad', 'Вибачте, але сталася помилка. Спробуйте пізніше.');
				}
			}
		}
		$this->render('_photo', array(
			'photo' => $model,
			'model' => $this->loadModel(Yii::app()->user->id)
		));
	}

	public function actionPhotoDel()
	{
		$user = User::model()->findByPk(Yii::app()->user->id);
		if (!is_null($user) && $user !== false && strlen($user->photo) == Yii::app()->params['photoLength']) { // sorry for dogs
			@unlink(Yii::getpathOfAlias('webroot') . Yii::app()->params['uploadFolder'] . $user->photo . '.jpg');
			@unlink(Yii::getpathOfAlias('webroot') . Yii::app()->params['uploadFolderTh'] . 't' . $user->photo . '.jpg');
			$this->setPhoto('');
		}
		$this->redirect(array('update', 'id' => Yii::app()->user->id));
	}

	public function setPhoto($name)
	{
		$command = Yii::app()->db->createCommand();
		if ($command->update('users', array(
				'photo' => $name,
			),
			'id=:id', array(':id' => Yii::app()->user->id))
		) {
			return true;
		}
		return false;
	}

	public function actionMail()
	{
		$this->setPageTitle('Розсилка');
		$form = new MailForm;
		if (isset($_POST['MailForm'])) {
			$form->attributes = $_POST['MailForm'];
			$u = User::model()->findAll();
			$mailer = Yii::app()->mail;
			foreach ($u as $a) {
				//send mail for everyone
				$mail = $mailer->newMessage(array(
					'subject' => $form->subject,
					'from'    => Yii::app()->params['mail'],
					'to'      => $a->email,
				));
				$mail->view = array('subscription', 'message' => $form->body);
				if (!$mailer->send($mail)) {
					Yii::app()->user->setFlash('fail', 'Помилка розсилки. Спробуйте пізніше.');
				}
			}
			if (!Yii::app()->user->getFlash('fail')) {
				Yii::app()->user->setFlash('success', 'Розсилка успішно відправлена.');
			}
			$this->refresh();
		}
		$this->render('mail', array(
			'model' => $form
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model = User::model()->findByPk($id);
		if ($model === null) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'user-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/news/_alumnus.php
<div class="item_user_news">
	<div class="user_news_title">
		<h3><?php echo CHtml::link ($data->title, array('/news/view', 'id' => $data->id)); ?></h3>

		<div class="user_news_edit">
			<?php if (Yii::app ()->user->id == $data->author_created->id): ?>
				<?php echo CHtml::link ('Редагувати', array('news/update', 'id' => $data->id)); ?>
			<?php endif; ?>
		</div>
	</div>

	<div class="category">[<?php echo $data->category->value; ?>]</div>

	<div class="user_news_text">
		<?php
			echo $data->content;
		?>
	</div>
	<div class="user_news_author">
		<?php echo CHtml::link ($data->author_created->surname . ' ' . $data->author_created->name, array('user/view', 'id' => $data->author_created->id,'name'=>($data->author_created->surname.'-'.$data->author_created->name))); ?>
		<b><?php echo date (Yii::app ()->params['date'], $data->created); ?></b>
	</div>

</div>

protected/views/news/_form.php
<?php Yii::import('ext.imperavi-redactor-widget.ImperaviRedactorWidget');?>
<?php
/* @var $this NewsController */
/* @var $model News */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'news-form',
	'enableAjaxValidation'=>true,
)); ?>

	<p class="note">Усі поля є обов’язковими.</p>

	<?php echo $form->errorSummary($model,'Виправте наступні помилки'); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'title'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'content'); ?>
		<?php echo $form->textArea($model,'content',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'content'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'type'); ?>
		<?php echo $form->dropDownList($model,'type',CHtml::listData(Lookup::model()->findAll(), 'id', 'value')); ?>
		<?php echo $form->error($model,'type'); ?>
	</div>
	<div class="row">
   		<?php Yii::import('application.extensions.CJuiDateTimePicker.CJuiDateTimePicker');?>
   		<label>Deadline</label>
		<?php
    		$this->widget('zii.widgets.jui.CJuiDatePicker', array(
    		'language'=>'en',
    		'model'=>$model,
    		'attribute'=>'deadline',
    		'options'=>array(
    		    'showAnim'=>'fold',
    		    'dateFormat'=>'mm-dd-yy',
    		),
   
    	'htmlOptions'=>array(
        'style'=>'height:20px;'
    	),
	)); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'status'); ?>
		<?php echo $form->dropDownList($model,'status', array('1'=>'Published','0'=>'Draft')); ?>
		<?php echo $form->error($model,'status'); ?>
	</div>

	<div class="form_button">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Додати' : 'Зберегти'); ?>
	</div>

        <?php
            $this->widget('application.lib.yiiext.imperavi-redactor-widget.ImperaviRedactorWidget', array(
                'selector'=>'#News_content',
                'options' => array(
                    'lang' => 'ua',
                    'minHeight'=>'150',
                ),
            ));
        ?>
<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/news/_search.php
<?php
/* @var $this NewsController */
/* @var $model News */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'content'); ?>
		<?php echo $form->textArea($model,'content',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'author'); ?>
		<?php echo $form->textField($model,'author'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'created'); ?>
		<?php echo $form->textField($model,'created'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'status'); ?>
		<?php echo $form->textField($model,'status'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/news/_view.php
<?php
/* @var $this NewsController */
/* @var $data News */
?>

<div class="news_view">
	<h2><?php echo CHtml::link(CHtml::encode(strip_tags($data->title)), array('news/view', 'id' => $data->id)); ?></h2>

	<p><?php echo $data->content; ?></p>
	<span class="news_date">Додано: <?php echo date(Yii::app()->params['date'], $data->created); ?>
        <?php if(strlen($data->deadline)>1):?>
        &nbsp; <font color="red">DEADLINE: <?php echo str_replace('-','.',$data->deadline);?></font>
        <?php endif;?>
    </span> <br>
</div>

protected/views/news/admin.php
<?php
/* @var $this NewsController */
/* @var $model News */

$this->breadcrumbs=array(
	'News'=>array('index'),
	'Manage',
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('news-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage News</h1>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'news-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'title',
		array(
			'name'=>'content',
			'value'=>'wordwrap(strip_tags($data->content),100,"<br />",true)',
			'type'=>'raw'
		),
		array(
			'name'=>'author',
			'value'=>'($data->author==0) ? "admin":$data->author_created->full_name'
		),
		array(
			'name'=>'created',
			'value'=>'date(Yii::app()->params[\'date\'],$data->created)'
		),
		array(
			'name'=>'status',
			'value'=>'($data->status==News::STATUS_PUBLISHED) ? "Опубліковано":"Чорновик"'
		),
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/news/alumnus.php
<?php
/* @var $this NewsController */
/* @var $dataProvider CActiveDataProvider */
$this->breadcrumbs = array(
	'Випусники'=>array('user/index'),
	'Новини випускників'
);
?>

<?php
#die(var_dump($dataProvider->getData()));
?>
<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_alumnus',
	'summaryText'=>'&nbsp;',
	'emptyText'=>'Випускники ще нічого не написали.',
	'template'=>"{items}\n{pager}",
)); ?>

protected/views/news/create.php
<?php
/* @var $this NewsController */
/* @var $model News */

$this->breadcrumbs=array(
	'Новини'=>array('index'),
	'Додати',
);
?>

<h1>Додати новину</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/news/index.php
<?php
/* @var $this NewsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = array(
	'Новини',
);
?>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider' => $dataProvider,
	'ajaxUpdate'   => false,
	'itemView'     => '_view',
	'emptyText'    => 'Новини відсутні.',
	'pager'        => array(
		'class'          => 'CLinkPager',
		'firstPageLabel' => '<<',
		'prevPageLabel'  => 'Назад',
		'nextPageLabel'  => 'Вперед',
		'lastPageLabel'  => '>>',
		'header'=>'На сторінку:'
	),
)); ?>

protected/views/news/update.php
<?php
/* @var $this NewsController */
/* @var $model News */

$this->breadcrumbs=array(
	'News'=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List News', 'url'=>array('index')),
	array('label'=>'Create News', 'url'=>array('create')),
	array('label'=>'View News', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage News', 'url'=>array('admin')),
);
?>

<h1>Update News <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/news/view.php
<?php
/* @var $this NewsController */
/* @var $model News */

$this->breadcrumbs = array(
	'Новини' => array('index'),
	strip_tags($model->title),
);
?>

<div class="user_fullnews">

	<h1><?php echo $model->title; ?>
		<?php if ($model->author != 0): ?>
			<div class="category">[<?php echo $model->category->value; ?>]</div>
		<?php endif; ?>

	</h1>

	<div class="user_fullnews_content"><?php echo $model->content; ?></div>

	<div class="user_fullnews_info">
		<div class="user_fullnews_date"><b><?php echo date(Yii::app()->params['date'], $model->created); ?></b></div>
		<div class="user_fullnews_author">
			<?php if (!is_null($model->author_created)) {
				echo CHtml::link(
					$model->author_created->surname . ' ' . $model->author_created->name,
					array(
						'user/view',
						'id'   => $model->author_created->id,
						'name' => ($model->author_created->surname . '-' . $model->author_created->name))
				);
			}?></div>
	</div>

</div>