protected/controllers/NewsController.php
<?php

class NewsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow all users to perform 'index' and 'view' actions
				'actions' => array('index', 'view', 'alumnus'),
				'users'   => array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions' => array('create', 'update'),
				'users'   => array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions' => array('admin', 'delete'),
				'users'   => array('admin'),
			),
			array('deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view', array(
			'model' => $this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new News;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['News'])) {
			$model->attributes = $_POST['News'];
			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array(
			'model' => $model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$this->setPageTitle("Редагування новин");
		$model = $this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['News'])) {
			$model->attributes = $_POST['News'];
			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
			'model' => $model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if (!isset($_GET['ajax'])) {
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex($user_id = null)
	{
		$this->setPageTitle("Останні новини");
		$dataProvider = new CActiveDataProvider('News', array(
			'criteria'   => array(
				'condition' => "`status`='" . News::STATUS_PUBLISHED . "'",
				'with'      => array('author_created', 'category'),
				'order'     => 'created DESC',
			),
			'pagination' => array(
				'pageSize' => 5
			)
		));
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAlumnus()
	{
		$this->setPageTitle("Новини від випускників");
		$user_news = new CActiveDataProvider('News', array(
			'criteria'   => array(
				'limit'     => 10,
				'order'     => 'created DESC',
				'condition' => "`author`!=0 and `status`='" . News::STATUS_PUBLISHED . "'",
				'with'      => 'author_created'
			),
			'pagination' => array(
				'pageSize' => 10,
			)
		));
		$this->render('alumnus', array(
			'dataProvider' => $user_news
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model = new News('search');
		$model->unsetAttributes(); // clear any default values
		if (isset($_GET['News'])) {
			$model->attributes = $_GET['News'];
		}

		$this->render('admin', array(
			'model' => $model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model = News::model()->findByPk($id);
		if ($model === null) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'news-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete, photodel', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow all users to perform 'index' and 'view' actions
				'actions' => array('create', 'index', 'view'),
				'users'   => array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions' => array('update', 'photo', 'photodel'),
				'users'   => array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions' => array('admin', 'delete', 'mail'),
				'users'   => array('admin'),
			),
			array('deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->setPageTitle('Профіль користувача');
		$this->render('view', array(
			'model' => $this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate($key)
	{
		$this->setPageTitle('Реєстрація користувача');
		if (!Yii::app()->user->isGuest) {
			Yii::app()->user->logout(); // logout user to be registreted
			$this->refresh();
		}
		if (strlen($key) != 32) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		$invite = Invite::model()->find('`key`=:key', array(':key' => $key));
		if ($invite === null || $invite->key !== $key) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		if ($invite->used == 1) {
			throw new CHttpException(404, "Вибачте, але це запрошення вже було використано.");
		}

		$model = new User;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);
		if (isset($_POST['User'])) {
			$model->attributes = $_POST['User'];
			if ($model->validate()) {
				$model->password = hash('sha512', $model->password);
				$model->save(false);
				$invite->used = 1;
				$invite->save();
				Yii::app()->user->setFlash('info', 'Щиро дякуємо за реєстрацію. Як тільки сайт запрацює на повну потужність, ми Вас обов’язково повідомимо листом.');
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$model->email = $invite->email;
		for ($i = 1992; $i < date('Y'); $i++) {
			$years[$i] = $i;
		}
		$this->render('create', array(
			'model' => $model,
			'years' => $years
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$this->setPageTitle('Редагування профілю');
		$model = $this->loadModel($id);
		if (Yii::app()->user->getState('email') !== $model->email && Yii::app()->user->name !== 'admin') {
			throw new CHttpException(404, 'The requested page does not exist.');
		}

		$this->performAjaxValidation($model);
		if (isset($_POST['User'])) {
			$pass = $_POST['User']['password'];
			$old_pass = $model->password;

			$model->attributes = $_POST['User'];
			$model->password = $old_pass;
			if (strlen($pass) >= 8 && $old_pass !== hash('sha512', $pass)) {
				$model->password = hash('sha512', $pass);
			}
			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		for ($i = 1992; $i < date('Y'); $i++) {
			$years[$i] = $i;
		}
		$model->password = '';
		$this->render('update', array(
			'model' => $model,
			'years' => $years
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if (!isset($_GET['ajax'])) {
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->setPageTitle('Випускники');
		$c = Yii::app()->db->createCommand();
		$users = $c->select()->from('users')->order('enter ASC,surname')->queryAll();
		foreach ($users as $u) {
			$users[$u['year']][] = $u;
		}
		$c->reset();
		$years = $c->select('year as year')->from('users')->group('year')->order('year DESC')->queryAll();
		$this->render('index', array(
			'users' => $users,
			'years' => $years
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model = new User('search');
		$model->unsetAttributes(); // clear any default values
		if (isset($_GET['User'])) {
			$model->attributes = $_GET['User'];
		}

		$this->render('admin', array(
			'model' => $model,
		));
	}

	public function actionPhoto()
	{
		$this->setPageTitle('Редагування фото');
		$model = new PhotoForm;
		if (isset($_POST['PhotoForm'])) {
			$model->attributes = $_POST['PhotoForm'];
			if ($model->validate()) {
				$model->image = EUploadedImage::getInstance($model, 'photo');
				$model->image->maxWidth = 240;
				$model->image->maxHeight = 320;
				$model->image->thumb = array(
					'maxWidth'  => 64,
					'maxHeight' => 64,
					'dir'       => 't',
					'prefix'    => 't',
				);
				$name = substr(md5(time() . Yii::app()->user->name), 0, Yii::app()->params['photoLength']).'.jpg'; // name of file
				if ($model->image->saveAs(Yii::getPathOfAlias('webroot') . Yii::app()->params['uploadFolder'] . $name)) {
					$this->setPhoto($name);
					Yii::app()->user->setFlash('img_good', 'Зображення було успішно змінено.');
				} else {
					Yii::app()->user->setFlash('img_bad', 'Вибачте, але сталася помилка. Спробуйте пізніше.');
				}
			}
		}
		$this->render('_photo', array(
			'photo' => $model,
			'model' => $this->loadModel(Yii::app()->user->id)
		));
	}

	public function actionPhotoDel()
	{
		$user = User::model()->findByPk(Yii::app()->user->id);
		if (!is_null($user) && $user !== false && strlen($user->photo) == Yii::app()->params['photoLength']) { // sorry for dogs
			@unlink(Yii::getpathOfAlias('webroot') . Yii::app()->params['uploadFolder'] . $user->photo . '.jpg');
			@unlink(Yii::getpathOfAlias('webroot') . Yii::app()->params['uploadFolderTh'] . 't' . $user->photo . '.jpg');
			$this->setPhoto('');
		}
		$this->redirect(array('update', 'id' => Yii::app()->user->id));
	}

	public function setPhoto($name)
	{
		$command = Yii::app()->db->createCommand();
		if ($command->update('users', array(
				'photo' => $name,
			),
			'id=:id', array(':id' => Yii::app()->user->id))
		) {
			return true;
		}
		return false;
	}

	public function actionMail()
	{
		$this->setPageTitle('Розсилка');
		$form = new MailForm;
		if (isset($_POST['MailForm'])) {
			$form->attributes = $_POST['MailForm'];
			$u = User::model()->findAll();
			$mailer = Yii::app()->mail;
			foreach ($u as $a) {
				//send mail for everyone
				$mail = $mailer->newMessage(array(
					'subject' => $form->subject,
					'from'    => Yii::app()->params['mail'],
					'to'      => $a->email,
				));
				$mail->view = array('subscription', 'message' => $form->body);
				if (!$mailer->send($mail)) {
					Yii::app()->user->setFlash('fail', 'Помилка розсилки. Спробуйте пізніше.');
				}
			}
			if (!Yii::app()->user->getFlash('fail')) {
				Yii::app()->user->setFlash('success', 'Розсилка успішно відправлена.');
			}
			$this->refresh();
		}
		$this->render('mail', array(
			'model' => $form
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model = User::model()->findByPk($id);
		if ($model === null) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'user-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/user/_form.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */

Yii::import('application.lib.yiiext.imperavi-redactor-widget.*');
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Поля позначені зірочкою є обов'язковими для заповнення.</p>

	<?php echo $form->errorSummary($model); ?>

	<div>
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>50,'maxlength'=>50)); ?>
        <p class="hint">Емейл використовується у якості логіну та ніде не відображається.</p> 
		<?php echo $form->error($model,'email'); ?>
	</div>
	<div>
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password',array('size'=>32,'maxlength'=>32)); ?>
		<?php echo $form->error($model,'password'); ?>
	</div>
<div class="separator"></div>
<div class="username_forms">
	<div>
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div>
		<?php echo $form->labelEx($model,'surname'); ?>
		<?php echo $form->textField($model,'surname',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div>
		<?php echo $form->labelEx($model,'middle_name'); ?>
		<?php echo $form->textField($model,'middle_name',array('size'=>20,'maxlength'=>20)); ?>
	</div>
</div>
<div class="separator"></div>
<div class="level">
	<label class="required">Вкажіть свій вчений ступінь (найвищий)
<span class="required">*</span>
	</label>
    <div>
    <?php
        echo $form->radioButtonList($model,'level',
          User::getLevels(),array('separator'=>'</div><div>'));
    ?>
	</div>
</div>
<div class="separator"></div>
	<div class="years">
		<?php echo $form->labelEx($model,'enter'); ?>
		<?php echo $form->dropDownList($model,'enter',array_combine(range(1991,date('Y')),range(1991,date('Y')))); ?>
		<?php echo $form->error($model,'enter'); ?>
	</div>
	<div class="years">
		<?php echo $form->labelEx($model,'year'); ?>
		<?php echo $form->dropDownList($model,'year',array_combine(range(1996,date('Y')),range(1996,date('Y')))); ?>
		<?php echo $form->error($model,'year'); ?>
	</div>
<div class="separator"></div>

<div class="detail_info">
	<div>
		<?php echo $form->labelEx($model,'info'); ?>
		<?php echo $form->textArea($model,'info',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'info'); ?>
	</div>

	<div>
		<?php echo $form->labelEx($model,'reason'); ?>
		<?php echo $form->textArea($model,'reason',array('rows'=>6, 'cols'=>50)); ?>
        <?php
            $this->widget('ImperaviRedactorWidget', array(
                'selector'=>'#User_reason,#User_info,#User_publications,#User_additional',
                'options' => array(
                    'lang' => 'ua',
                    'minHeight'=>'150',
#                    'air'=>true,
                    'fixed'=>false,
                    'fixedBox'=>false,
                ),
        ));?>
		<?php echo $form->error($model,'reason'); ?>
	</div>
	<div>
		<?php echo $form->labelEx($model,'publications'); ?>
		<?php echo $form->textArea($model,'publications',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'publications'); ?>
	</div>

	<div class="additional_info">
		<?php echo $form->labelEx($model,'additional'); ?>
		<?php echo $form->textArea($model,'additional',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'additional'); ?>
	</div>

</div>

<div class="separator"></div>

<div class="final_info">
	<div>
		<?php echo $form->labelEx($model,'url'); ?>
		<?php echo $form->textField($model,'url'); ?>
		<?php echo $form->error($model,'url'); ?>
	</div>
	<div>
		<?php echo $form->labelEx($model,'university'); ?>
		<?php echo $form->textField($model,'university',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'university'); ?>
	</div>

	<div>
		<?php echo $form->labelEx($model,'wish'); ?>
		<?php echo $form->textField($model,'wish',array('size'=>60)); ?>
		<?php echo $form->error($model,'wish'); ?>
	</div>
    
    <div>
    <?php if(Yii::app()->controller->action->id == 'update'):?>
        <?php echo CHtml::link(strlen($model->photo) == Yii::app()->params['photoLength'] ? 'Змінити фото':'Додати фото', array('user/photo'));?>
    </div>
    <?php if(strlen($model->photo) == Yii::app()->params['photoLength']):?>
       <?php echo CHtml::link('Видалити фоточку',"#", array("submit"=>array('photodel'), 'confirm' => 'Точно хочете повернути стандартну унилу фоточку?')); ?> 
    <?php endif;?>
    <?php else:?>
        Завантажити фото можна буде після реєстрації. <br/>Редагувати свій профіль Ви зможете в будь-який момент залогінившись на сайті.
    <?php endif;?>
</div>

<div class="separator"></div>
	<div class="form_button">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Зареєструватись' : 'Зберегти'); ?>
	</div>
<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/user/_photo.php
<?php
$this->breadcrumbs=array(
	'Випускники'=>array('index'),
	$model->surname.' '.$model->name=>array('view','id'=>$model->id),
	'Оновлення'=>array('update','id'=>$model->id),
    'Фоточка'
);?>
<div class="form">
    <?php if(Yii::app()->user->hasFlash('img_good')):?>
    <div class="error success">
        <?php  echo Yii::app()->user->getFlash('img_good'); ?>
    </div>
    <?php endif;?>

    <?php if(Yii::app()->user->hasFlash('img_bad')):?>
    <div class="error fail">
        <?php  echo Yii::app()->user->getFlash('img_bad'); ?>
    </div>
    <?php endif;?>

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-form',
	'enableAjaxValidation'=>false,
    'htmlOptions' => array('enctype' => 'multipart/form-data'),

));?>
	<?php echo $form->errorSummary($photo); ?>

	<div>
		<?php echo $form->labelEx($photo,'photo'); ?>
		<?php echo $form->fileField($photo,'photo'); ?>
	<div class="form_button">
		<?php echo CHtml::submitButton(strlen($model->photo)==Yii::app()->params['photoLength']?'Змінити фото':'Додати фото'); ?>
	</div>
<?php $this->endWidget(); ?>
</div>

protected/views/user/_view.php
<?php
/* @var $this UserController */
/* @var $data User */
if($tmp_year!=$data->year) //hack for view every year in new line. Here Vadik must insert some html div or something else
    echo "<br/>";
?>
<a href="<?php echo Yii::app()->createUrl('user/view',array('id'=>$data->id));?>">
<div class="user_shortview">
	<div class="user_photo"><img src="<?php echo strlen($data->photo)==10 ? Yii::app()->params['uploadFolderTh'].'t'.$data->photo.".jpg":"http://placehold.it/64/000000" ;?>"></div>
	<div class="user_name">
	<?php echo $data->surname.'<br>'.$data->name; ?>
	</div>
	<div class="user_endyear">
	<?php echo CHtml::encode($data->enter.'-'.$data->year); ?>
	</div>
</div>
</a>

<?php
    $tmp_year = $data->year;
?>

protected/views/user/admin.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('user-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Users</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'user-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'email',
		'name',
		'surname',
		'middle_name',
		/*
		'info',
		'reason',
		'year',
		'university',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/user/index.php
<?php
/* @var $this UserController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = array(
	'Випускники',
);
?>

<div class="user_countainer">
	<div class="random_users">
		<div id="filter">
			<ul>
				<?php foreach ($years as $year): ?>
					<li><?php echo CHtml::link($year['year'], array('user/index', '#' => $year['year'])); ?></li>
				<?php endforeach; ?>
			</ul>
		</div>
		<div class="items">
			<?php foreach ($years as $year): ?>
				<div class="users_year"><a name="<?php echo $year['year']; ?>"><?php echo $year['year']; ?></a></div>
				<?php foreach ($users[$year['year']] as $user): ?>
					<a href="<?php echo Yii::app()->createUrl('user/view', array('id' => $user['id'], 'name' => ($user['surname'] . '-' . $user['name']))); ?>">
						<div class="user_shortview">
							<div class="user_photo">
								<img src="<?php echo User::getPhoto($user['id'], true);?>">
							</div>
							<div class="user_name">
								<?php echo $user['surname'] . '<br/>' . $user['name']; ?>
							</div>
							<div class="user_endyear">
								<?php echo CHtml::encode($user['enter'] . ' / ' . $user['year']); ?>
							</div>
						</div>
					</a>
				<?php endforeach; ?>
			<?php endforeach; ?>
		</div>
	</div>
</div>

protected/views/user/view.php
<?php
/* @var $this UserController */
/* @var $model User */


$this->breadcrumbs = array(
	'Випускники' => array('index'),
	$model->full_name
);
?>
<?php if (Yii::app()->user->hasFlash('info')): ?>
	<div class="info">
		<?php echo Yii::app()->user->getFlash('info'); ?>
	</div>
<?php endif; ?>
<h1 class="user"><span>Випускник:</span> <?php echo $model->surname . ' ' . $model->name . ' ' . $model->middle_name; ?>
</h1>

<div class="user_control_buttons">
	<?php if ($model->id == Yii::app()->user->id): ?>
		<div><?php echo CHtml::link('Редагувати', array('user/update', 'id' => Yii::app()->user->id)); ?></div>
		<div><?php echo CHtml::link('Додати новину', array('news/create')); ?></div>
	<?php endif; ?>
</div>

<div class="user_container">

	<div class="user_leftpanel">

		<div class="user_fullphoto">
			<img
				src="<?php echo User::getPhoto($model->id);?>">
		</div>

		<?php if (strlen($model->university) > 1): ?>
			<div class="user_workplace">
				<?php echo $model->university; ?>
			</div>
		<?php endif; ?>

		<?php if (strlen($model->url) > 1): ?>
			<div class="user_personal_page">
				<a href="<?php echo $model->url; ?>" title="Персональна сторінка"><?php echo $model->url; ?></a>
			</div>
		<?php endif; ?>
		<div class="user_years">
			<span title="Рік вступу"><?php echo $model->enter; ?></span>
			<span title="Рік випуску"><?php echo $model->year; ?></span>
		</div>

		<div class="user_level">
			<?php
			//begin rendering educational level
			$a = User::getLevels();
			if (isset($a[$model->level])) {
				echo $a[$model->level];
			} else {
				echo "Бакалавр";
			} //default value, if it haven't been checked
			//end rendering
			?>
		</div>

	</div>

	<div class="user_rightpanel">

		<?php if (strlen($model->info) > 1): ?>
			<div class="user_cv">
				<h3 class="user_block_title">CV</h3>
				<?php echo $model->info; ?>
			</div>
			<span class="divider"></span>
		<?php endif; ?>

		<?php if (strlen($model->publications) > 1): ?>
			<div class="user_publication">
				<h3 class="user_block_title">Публікації</h3>
				<?php echo $model->publications; ?>
			</div>
			<span class="divider"></span>
		<?php endif; ?>

		<?php if (strlen($model->wish) > 1): ?>
			<div class="user_advice">
				<h3 class="user_block_title">Порада абітурієнтам</h3>

				<div class="user_advice_text"><?php echo $model->wish; ?></div>
			</div>
			<span class="divider"></span>
		<?php endif; ?>

		<?php if (strlen($model->reason) > 1): ?>
			<div class="user_advice">
				<h3 class="user_block_title">Чому варто навчатись на фіз-мат кафедрі НаУКМА</h3>

				<div class="user_advice_text"><?php echo $model->reason; ?></div>
			</div>
			<span class="divider"></span>
		<?php endif; ?>

		<?php if (strlen($model->additional) > 1): ?>
			<div class="user_additional">
				<h3 class="user_block_title">Хоббі, додаткова інформація</h3>

				<div class="user_additional"><?php echo $model->additional; ?></div>
			</div>
		<?php endif; ?>

	</div>
</div>